### ISSUE TITLE
Pull should ask for credentials

### ISSUE THREAD

**Issue by amintos** [hpi-swa/Squot#103]
At the moment, `GitRemoteAuthenticationFailed` spawns a debugger when the user clicks "pull" on a previously cloned, **private** GitHub repository. I suggest to catch `GitRemoteAuthenticationFailed` in `SquitBrowser >> actionPull` the way it is done in `actionBranchPush` and subsequently refactor to a more centralized "401-catcher".

**Comment by j4yk** [comment]
> refactor to a more centralized "401-catcher".

Conincidentally, such thing appeared just yesterday. ;-)

The problem is that in `actionPull`, the SquitRepository is not involved in the send to `fetchFrom:`, so it has no chance to provide credentials. Unlike in `actionBranchPush` which goes via `exportToUpstream:ifNone:` of the SquitRepository. I will fix this tomorrow and apply the new "catcher" underway, so it will prompt for credentials if none are stored yet.
