### ISSUE TITLE
Prevent accidental deletion of uncommitted changes upon checkout of another branch

### ISSUE THREAD

**Issue by Lariiii** [hpi-swa/Squot#106]
Squot deletes uncommitted changes when switching branches without warning.

**Comment by j4yk** [comment]
Sorry, but this is impossible because the 'Switch branch' menu item does not load or discard anything in the object memory. It currently merely sets to which branch new commits will go.

Or are you talking about files which are not handled by Squot (which would be prone to #53)?

So what steps exactly did you take before you found your changes to be lost? You can recover them from the changes file with Extras > Recover changes... by the way.

**Comment by feeds** [comment]
I think this happend when a checkout of another branch was performed. Maybe a warning like 'You are overwriting local changes' could be added (= a more explicit version than the Dialog Box appearing 'Do you want to file in new changes?')

Luckily the recover changes worked well :)

**Comment by j4yk** [comment]
When you use the Git browser, all code paths that load something go through the dialog that allows you to select changes. So nothing should be "silently" overwritten.

The "Checkout" menu item, as it currently works, does not switch branches, but is used to load code from another commit, using the mentioned dialog. It allows you to discard/revert the uncommitted changes, indeed. But you should have been able to deselect the stuff that you want to keep.

So my guess is that the underlying problem is that it is not entirely clear what the "Checkout" menu item does and, consequently, that one has to be careful with uncommitted changes when you use it. Would you agree?

**Comment by feeds** [comment]
I agree, I guess we just accepted all the new changes and were surprised to find that ours had been overwritten.

On that matter - when I am using the GitBrowser and I want to work on another branch  I always switch a branch and then checkout the first commit. Is this the right procedure? How can I be sure that something like uncommited changes don't get lost (or at least that there are no uncommited changes anymore)?

**Comment by j4yk** [comment]
Currently, this is the correct procedure if you want to load the code from the other branch. In the selection dialog that opens when you click "Checkout", you have to manually make sure to deselect each change that reverts something of your uncommitted changes.

So far, the only way to check that there are no uncommited changes is to click Commit and see that there are no changes to be committed...

Tom Beckmann and I implemented a feature some days ago that simulates a merge with the uncommitted changes (like Monticello's "Merge" button does), so the uncommitted changes do not have to be deselected manually and if there are conflicts between uncommitted changes and the version selected for loading, the user is prompted to resolve them. Does this sound better to you?

For comparison, the original Git behavior of a branch-switching checkout would be to keep uncommitted changes, but reject the checkout when a "dirty" file needs to change. [Gitless](http://www.gitless.com) defines a "switch" command that automatically stashes uncommitted changes on the old branch and provides a --move-over option to explicitly take uncommitted changes to the new branch.

I will probably change the "Switch branch" action in the Git browser to do something similar like Gitless (or have it invoke the new feature from above) in the future. So far, I often did not want to actually load the other branch and preferred to sort out the changes in the save dialog instead. But my workflow might be "too special" since the project I am working on is Squot itself and I cannot test new features when they are unloaded every time I switch branches, or worse, state would horribly break all the time. ;-)

**Comment by feeds** [comment]
I think we would mostly use this for quickly switching to another branch for a review of another feature. In my opinion the github diffs from the pull requests are not clear enough for understanding somthing like structural changes in the code, which is why I want to have a look at it within the image.

Something like gitless would be very nice. Otherwise I should be promted to commit my changes if I want to keep them, because I dont want to have them in the image when I review the other branch.

**Comment by j4yk** [comment]
@feeds Would you and the rest of your team like to field-test the new branch switching behavior? IIRC some of you already used Squot from the develop branch, but in case not, you can redirect the self-update by changing the branch in `SquitBrowser class>>selfUpdateFromMetacello`, or, if you have a project in the Git browser whose name includes 'Squot', in `SquitBrowser class>>selfUpdateWithSquot:` (since the update will overwrite the method, you will have to change or revert it every time).

I think it makes sense to give this to you earlier because your team seems to do a lot of branching. I would like to know if the behavior is more expected now and if I have missed some use case that is not easily covered.

**Comment by feeds** [comment]
Thanks a lot! At least I am using it now, maybe the others want to try it too ... 
@Lariiii @baschdl @bjrne @blubl
 I'll keep you updated about strange behaviour!

**Comment by j4yk** [comment]
Let's hope there is no strange behavior, but in case you might ask yourselves at some point where your uncommitted changes went: For now, they are stored in git references that start with `refs/meta/squot-stash-...`, for example `refs/meta/squot-stash-refs/heads/master`. In gitk they are displayed like this:

![image](https://user-images.githubusercontent.com/151175/27870170-7a89f348-61a2-11e7-81e5-ce31402c4e20.png)
(the "Local changes checked in to index but not committed" item is unrelated because of the unsynced file system working copy)
It might be better to include the image name in those refs in the future, like already done for that other meta ref that can be seen in the screenshot.

These references are overwritten on each switch away, but they have a reflog like regular branches. So just in case something does go missing, the reflog is another place to look for it.

**Comment by j4yk** [comment]
I will consider this resolved until somebody tells me otherwise.
