### ISSUE TITLE
New package can not be tracked until superpackage is untracked

### ISSUE THREAD

**Issue by feeds** [hpi-swa/Squot#121]
Given the packages `GANA-tests` `GANA-UI` `GANA-Core` , `GANA-Baseline` and `GANA` we added another package `GANA-Performance` We were not able to track it via the context menu of the Repo, until we untracked `GANA`. Only then it would appear in the seletion for the packages available for tracking.

Did we do anthing wrong by selecting the tracked packages? (eg `GANA` musnt be included)
Otherwise, `GANA-Performance` should have appeared in the list without removing  `GANA`.

**Comment by j4yk** [comment]
When you track `GANA`, the category `GANA-Performance` is automatically included, as are all the other categories/packages you mentioned (that's how PackageInfo works). Thus, if it were possible to add the subcategory packages while the supercategory package is already tracked, the code would be duplicated in the file tree.

The correct procedure is therefore to decide on a granularity for the packages (how you want your code to be sliced) and then track the categories that match the desired package names exactly. This should be done at the same "level" of subcategories for all the packages because of the PackageInfo inclusion rules that I mentioned above.

To avoid the problem of the "superpackage" that includes all the categories, one can track the level below. The usual split is in "-Core" and "-Test". In Monticello you would have to commit each package seperately, which can be annoying. In Squot you can commit them all together, so that is not a problem. The remaining thing to consider for the package slicing is which parts are mandatory to load and which parts are optional (and dependency issues that might arise from this) or platform specific (Squeak/Pharo/..., versions of the former, OS, ...).
