### ISSUE TITLE
Automatically set upstream branch when creating local branch based on an origin one

### ISSUE THREAD

**Issue by bjrne** [hpi-swa/Squot#127]
Currently, when selecting "Create new branch and switch to it", I have to set an upstream branch manually again. Maybe this is intended behaviour, but I think in 99% I'd want to push to the same branch again or locally explicitly create another, differently named branch in order to avoid confusion.

**Comment by j4yk** [comment]
Hmm, when you checkout -b a new branch in Git, it does not have an upstream configuration. There are two intended use cases for "create branch and switch to it": 1) loading that commit temporarily to have a look at it—should not need an upstream branch—and 2) branch off from a commit that might not be the tip of the current branch—should get a new upstream setting because this is a new branch (as in "stream of development") after all.

How are you using the feature?

**Comment by j4yk** [comment]
When creating a local branch from a remote tracking one, you are probably correct. Checking out remote tracking branches in Git also creates a new local branch that is automatically set up to track the same remote branch.
