### ISSUE TITLE
Merge without common ancestor removes artifacts from the left that are not present on the right

### ISSUE THREAD

**Issue by Jeilef** [hpi-swa/Squot#166]
If I add a package to my local repo Version, then pull, the Dialog tells me that my package is removed instead of added.
Local merge:
![image](https://user-images.githubusercontent.com/18723935/38380407-eaec6ca4-3903-11e8-99c6-853f8144bd2d.png)

Remote Version:
![image](https://user-images.githubusercontent.com/18723935/38380442-08b4880c-3904-11e8-82a9-8e8613f9c3e1.png)

Here is the state of my Image:
![image](https://user-images.githubusercontent.com/18723935/38380485-2d146ba4-3904-11e8-9b40-9475cd0d55cd.png)

**Comment by j4yk** [comment]
@Jeilef I have changed the fallback behavior of merges without common ancestors to take an empty snapshot as the base. It should no longer propose to remove the loaded package in your situation.

**Comment by Jeilef** [comment]
It did not remove the package. On origin/master the package was not present and on my master the package is present. The Problem I was reporting is that when I try merging the master into origin/master the diff is: remove package. Hence you would expect the package is removed after the merge is finished. Confusingly but luckily the package was not removed

**Comment by j4yk** [comment]
That the package was not removed could actually be another issue: #122. Due to the auto-detection (and auto-adding, by folder name) of packages when they are encountered in file trees, it can in fact be hard to remove them from a working copy (that is, you have to try it multiple times). I have not thoroughly analysed that problem, though.

Is the diff display for your merge situation improved now, so may I close this issue?

**Comment by j4yk** [comment]
I assume this to be resolved. Please reopen if you feel that is not the case.
