### ISSUE TITLE
Squeak 5.1 Push to local, currently checked out branch doest ask you to set upstream

### ISSUE THREAD

**Issue by Jeilef** [hpi-swa/Squot#167]
You can click "Push" when having the local currently checked out branch selected. This results in a failed authorization. I think it would be way more intuitive if the tool would ask you which remote branch to push to if you havent one selected.
Current Git state:
![image](https://user-images.githubusercontent.com/18723935/38381128-1ecd694a-3906-11e8-9e42-c7470bd7bd19.png)

Error:
![image](https://user-images.githubusercontent.com/18723935/38381107-0cf54152-3906-11e8-9598-c0f45079644b.png)

When switched to remote:
![image](https://user-images.githubusercontent.com/18723935/38381167-37755610-3906-11e8-8486-1dab3ee496e3.png)

It asks you to set a upstream branch and the pushing works

**Comment by j4yk** [comment]
Actually, for fresh branches, it should prompt you for the remote name and URL when you push for the first time. Did it not? Was this repository cloned or created via "add project"? Or rather, did master already have an upstream branch set for which the credentials were missing for some reason? You can also try to change the upstream from the context menu of the local branch. The credentials for each remote can be set from the context menu of the project.
![image](https://user-images.githubusercontent.com/151175/38390910-ffbb7c8c-3922-11e8-89f4-34ad46054b5f.png)
![image](https://user-images.githubusercontent.com/151175/38390944-169528cc-3923-11e8-8741-f20f95b26bcb.png)

That you can invoke "push" on a remote-tracking branch (origin/master) is actually an error. One should not be able to push those because the only (official) way to ever change them is through 'fetch' (or 'push' on a tracking local branch). So it is never actually useful to push a remote-tracking branch. However, since it is a git reference just like the local branch is, pushing it works fine, technically, as it did for you.

**Comment by j4yk** [comment]
Note that there seems to be another intermittent bug that causes the "Authentication with the remote failed. ..." error. Another symptom is a debugger appearing with 401 Authentication Required (even though the credentials are supplied). Like for the ever-disturbing push bug #9, the workaround is to simply try again...

**Comment by Jeilef** [comment]
master did not have an upstream branch set yet.

**Comment by j4yk** [comment]
When I clone a rather empty repository and press push for the first time, I get this, as expected:
![image](https://user-images.githubusercontent.com/151175/38779026-c4baf548-40c2-11e8-9dae-261fb136de42.png)

It would be better if the clone branch would already be set up to track the cloned remote branch... But mainly it seems like cannot reproduce your error.

**Comment by j4yk** [comment]
Closed due to inactivity and no recent reports of a similar issue.
