### ISSUE TITLE
Pulling on a different machine after removing a package raises Error

### ISSUE THREAD

**Issue by tom95** [hpi-swa/Squot#172]
![image](https://user-images.githubusercontent.com/4313751/38661220-5ec9fac0-3e30-11e8-9fae-c365c98cab41.png)
I get this trace when I remove a package, push, switch to another machine and attempt to pull. Both machines were using the `develop` branch.

**Comment by j4yk** [comment]
Can you confirm that theirDiff is a SquotArtifactRemoval? What does `myDiff hasChanges` return?
- If the answers are yes and true, then #couldBeMergedWith: is wrong.
- If the answers are yes and false, something went wrong further up the stack, because the diff without changes should not be in `patchToMe`.
- If the first answer is no, then something went wrong during the saving of the removal; please check the files of that version in this case.

**Comment by tom95** [comment]
![image](https://user-images.githubusercontent.com/4313751/38669489-d487cc54-3e46-11e8-8d75-ff1e08e18aed.png)
It's yes and true, however both are ArtifactRemoval. Both removals have in `left` a SquotLazyArtifact with identical paths and in `right` `nil`.

**Comment by j4yk** [comment]
Well, these should be made compatible and merged conflict-free, of course... Seems like I overlooked another case.

Since ArtifactDiffs know their input artifacts (left, right), it might be better to send that merge message in the line where the error occurred to the diffs (myDiff, theirDiff) instead of grabbing the artifacts from the snapshots again. The removals could then sort themselves out.

**Comment by tom95** [comment]
Uh, is this something I could try? If so, please explain more detailed, I'm not quite sure yet what to do/move around :)

**Comment by j4yk** [comment]
If you have the time, please do. :-) I cannot do it today.

There are many cases of double dispatch in Squot already, so another for merging two ArtifactDiffs will not hurt. Regular ArtifactDiffs should eventually send the same message that you can see in the failing method to their `right`s. SquotArtifactRemoval could instead just answer itself if the other diff also #isRemoval. Not sure whether this should happen in the first stage or second stage of the double dispatch, though. You will have to send the `base` determined by the failing method along the dispatch as a parameter.

**Comment by tom95** [comment]
I'm not sure which messages you mean, since the method is rather long. However, while digging around I found that replacing `SquotArtifactRemoval>>couldBeMergedWith:` with just `^ false` fixed the problem, apparently. I would assume that this isn't a proper fix though.

**Comment by j4yk** [comment]
I was referring to #mergeDiffWith:basedOn: but did not want to type it on my phone. ;-) Two removals of the same thing can be merged, so an unconditional false in #couldBeMergedWith: is not accurate, even if it works.

**Comment by j4yk** [comment]
Turns out that I have already implemented what I described [above](https://github.com/hpi-swa/Squot/issues/172#issuecomment-380854188) in January for cherry-picking. But it was not used for regular merges, yet.

I changed the behavior when something is removed on both branches to not display a change at all, since the object is already gone where you want to conduct the merge. Please reopen if there is another issue with this.
