### ISSUE TITLE
Package Selection UI clarification

### ISSUE THREAD

**Issue by tom95** [hpi-swa/Squot#178]
Whether to track packages individually or by prefix keeps being a constant source of confusion for me. Is there the "canonically correct" way? Do both offer advantages? I now ran into a problem where I originally wanted to track packages individually, but then had a conflict in this scenario:
```
MyPackage-Core
MyPackage-Core-Tests
```
If possible, I believe it could be beneficial to clarify the best pratice in the README or wiki.

**Comment by tom95** [comment]
To me, having them tracked separately would be the best case, because it makes exploring the repo easier (not everything in a single folder). However, it appears that tracking separately is not possible at all with the above case (-Tests suffix), so I would tend to recommend tracking by prefix, because cleaning this up later, when one runs into an issue like the above, is rather annoying. But maybe (hopefully?) I'm lacking some insights.

**Comment by fniephaus** [comment]
`MyPackage-Core` is the prefix of `MyPackage-Core-Tests` and therefore a parent of it.
The recommended package structure is:
```
MyPackage-Core
MyPackage-Tests
MyPackage-Support
...
```
This way, you could track everything at once (via `MyPackage`), or, and that's the better way, each sub package independently.

**Comment by tom95** [comment]
In my particular case I wanted to split the tests packages as well. I had a colorful potpourri of classes that slowly amassed in my general tests category, so I thought splitting them could be nice. I do see how this might be a special use case not seen in many applications though.

**Comment by fniephaus** [comment]
Here's one way you could solve this:
```
MyPackage-Core
MyPackage-Support-Core
MyPackage-Support-Tests
MyPackage-Tests
...
``

**Comment by j4yk** [comment]
Adding both a top-level package and a lower-level "subpackage" at the same time will only add the higher-level one to the working copy. See #choosePackagesFromCategoriesFor:

```
selection := selection reject: [:each |
		selection anySatisfy: [:other | (each beginsWith: other) and: [each size ~~ other size]]].
```

But you can still get the duplication in the repository if you first add the "subpackage" and afterwards add the more general category prefix. I am open to suggestions. The space in the selection dialog itself is rather limited, otherwise I would propose to explain things there.

**Comment by fniephaus** [comment]
Is it possible to automatically unselect subpackages in the view when the correspondig top-level package is selected? Nonetheless, duplication is to be avoid I think, so there should at least be a check and an error message.

**Comment by j4yk** [comment]
Not without extending the UIManager's list chooser, I assume...

Do you mean you want to lecture users who have selected redundant entries in one pass?

**Comment by j4yk** [comment]
We could create a proper package selection dialog with two panes: a tree of the category "hierarchy" on the left, the selected packages on the right and ">" and "<" buttons in the middle to add and remove an item to/from the right list, respectively. Since this window would be larger anyway, the instruction text could also be put there.

But to be honest, I would prefer if one of you guys would implement that.

**Comment by tom95** [comment]
Thanks for the input @j4yk and @fniephaus . I think I now have enough knowledge about the implications to tackle creating a more comprehensive interface for this in the near future.

I will just take the liberty to rename this issue accordingly and assign myself.

**Comment by fniephaus** [comment]
Thanks, @tom95!
