### ISSUE TITLE
Packaging hierarchy enforced too strongly

### ISSUE THREAD

**Issue by krono** [hpi-swa/Squot#193]
## Situation

Existing packages in image as follows:

 - `SwaLint-Tests` with around 6..8 Classes (bla-TestCase etc.)
 - `SwaLint-Tests-Data` with around 20 Classes representing fixtures

## Expected behavior

After adding, config, commit etc., have the following filetree folders:
```
SwaLint-Tests.package
SwaLint-Tests-Data.package
```

## Actual behavior

See https://github.com/hpi-swa-teaching/SwaLint/tree/develop/packages : 
Only 
```
SwaLint-Tests.package
```
exists and contains all classes from both packages.

**Comment by krono** [comment]
(cc @fniephaus for followup of short discussion)

**Comment by j4yk** [comment]
This would duplicate the classes contained in Tests-Data. This is not a limitation or feature of Squot, but of PackageInfo. Is this really what you want?

**Comment by j4yk** [comment]
Or do you merely wish that "subpackages" go into their own folders (determined by the categorization of classes)? I would expect that this would be a change in serialization that is incompatible with Cypress/FileTree because they expect one folder per actual package. That is, if you would load such a Squot repository with FileTree and load the SwaLint-Tests package, it would not load the SwaLint-Tests-Data package.

Also, if you loaded both separately with FileTree and then saved SwaLint-Tests in Monticello, it would put all the classes of SwaLint-Tests-Data into `SwaLint-Tests.package` again.

**Comment by fniephaus** [comment]
@krono said he thinks that it used to be possible to export packages and their subpackages separately. Not sure if this really is the case. Let's wait for him to comment :)
