### ISSUE TITLE
Don't use SquotDiffNode title as identifier

### ISSUE THREAD

**Issue by LeonBein** [hpi-swa/Squot#210]
In SquotChangedArtifactsChooser#rootNodes and SquotDiffNodesExplorer#rootNodes the paths of the artifact diffs are used as titles for the diff nodes. In multiple methods, for instance in SquotChangedArtifactsChooser, this title is used as identifier back to the diffs.

As a developer for a squot extension I want to specify a title independently of the path/identifier of the artifact in order to communicate what the artifact is rather than on which path it operates. Implicitly using the title as identifier also seems like bad style somehow.

**Comment by j4yk** [comment]
Yep, that's technical debt and should be changed.

I have already refactored the handling of diff nodes here: https://github.com/j4yk/Squot/tree/feature/diff-tree-refactoring, but it did not completely get rid of the dependency between top node title and artifact path yet.

Note that you can add the same object under multiple paths in your repository, and the stored versions need not necessarily be equal at each path (since you can omit changes from commits at one path and include them at another path). So you should ensure that users can still distinguish those in the view. Although I admit that it is usually not really useful to have the same thing at different paths... unless, maybe, you have platform-specific variants of a package (or something else) next to each other and they still share the same identifying features (such as a package name). But I have no practical experience with that.
