### ISSUE TITLE
More specific author labels

### ISSUE THREAD

**Issue by marceltaeumel** [hpi-swa/Squot#226]
![squot-authorinitials](https://user-images.githubusercontent.com/5765308/55170370-aeabdb80-5176-11e9-9acd-2864db2a5868.png)

Using `SystemNavigation authors` and `Utilities authorInitials`, the string representations of authors in the Git Browser could be more specific. Maybe like this:  

```Smalltalk
author := SystemNavigation authors
		at: author
		ifPresent: [:initials | (initials includes: Utilities authorInitials)
			ifTrue: ['-- me --'] ifFalse: [(initials ifEmpty: ['?'] ifNotEmpty: [:i | i someElement]), ' (', (author contractTo: 16), ')']]
		ifAbsent: [author contractTo: 16].
```

**Comment by j4yk** [comment]
Interesting, but I would not want to see the author initials for proper Git commits (as opposed to Monticello-converted commits). It wastes previous space in the list and the initials alone would not be enough for me.

**Comment by marceltaeumel** [comment]
That's for your local views (or tools) only. Nothing of that is persisted on Git.

**Comment by j4yk** [comment]
Yes, I understood that it is only for the view, but I would not like that view for commits I created with either Git or Squot. I think the author initials are a remnant of Monticello and older times and I wonder why Squeak still prefers them. ;-)

**Comment by marceltaeumel** [comment]
In this case, it is just an integration of an existing data source that reveals more information about the authors. It would be nice if Squot could provide ways to attach such data sources.

**Comment by j4yk** [comment]
So you prefer to see the initials even though nothing in the Git commit info uses the initials?

Or are we talking about a converted Monticello history? In the latter case, I would rather propose to use the additional data source in the converter. Although I think it would take the wrong name for my person because someone else has used "jr" before me.

Pluggable data sources for the version authors sounds like an overkill to me, don't you? After all, the history already has author information, so why do we really need to extend that even further? Also, fancy author information does not sound like the most important feature to me. :-)

**Comment by marceltaeumel** [comment]
Well, I think this discussion about interactive tooling for Squot leads to an entirely different project. 😄

**Comment by j4yk** [comment]
Not sure what kind of tooling you mean, so I don't know whether I shall close the ticket or not. ;-)
