### ISSUE TITLE
Project list in Git Browser broken after latest Squeak Trunk updates

### ISSUE THREAD

**Issue by j4yk** [hpi-swa/Squot#243]
When I click on another project, the visual selection stays at the top project, even though the other panes of the browser are updated. However, I cannot select the top project anymore because, visually, it still is selected, in contrast to the state of the model. Moving the selection with the up and down keys also does not work.

The list uses index-based access via the variable projectIndex in SquitBrowser.

@marceltaeumel Can you please have a look or delegate to the colleagues who were involved in the latest list morph changes? If I used the API wrong, please suggest a fix.

**Comment by marceltaeumel** [comment]
Yes, due to a different caching strategy in pluggable lists, faulty (or lazy) models might reveal such effects now.

- `PluggableListMorph >> #verifyContents` does not work because your model (i.e., `SquitBrowser`) is no `CodeHolder`, which implements `#stepIn:` etc. for the "smart updating" preference.
- The model `SquitBrowser` fails to tell the views about the new selection in `#refresh`.

![grafik](https://user-images.githubusercontent.com/5765308/67757725-a41f3080-fa3c-11e9-8263-2f60453fc4bb.png)

**Comment by j4yk** [comment]
So an observer notification was indeed missing and went previously unnoticed due to side effects. Tragic. Thank you for the analysis!
