### ISSUE TITLE
objectReplacedByNames

### ISSUE THREAD

**Issue by marceltaeumel** [hpi-swa/Squot#259]
In the latest dev version, what does the following entry in the commit dialog mean?

![grafik](https://user-images.githubusercontent.com/5765308/74663700-8a952680-519c-11ea-86d9-dfa931bf95f9.png)

**Comment by j4yk** [comment]
It is a surfacing implementation detail. It is irrelevant for packages and it does not matter whether you accept or reject the change from the commit.

The property is part of the metadata for the tracked object graph. There one can for example annotate that a property of a specific object should not be captured. On serialization, the direct references to other objects are replaced by the names of these objects (indirection). This metadata property denotes whether the indirection was introduced or not.

Before I implemented the merge refactoring, changes in metadata were not displayed at all, and could not be controlled.

However in this case it would be correct to hide it, because the property is an internal detail of Squot itself.

**Comment by marceltaeumel** [comment]
Well, you could add an extra node for such meta information.

**Comment by j4yk** [comment]
You mean like the parent nodes for classes? Yes that is feasible.
