### ISSUE TITLE
Undeclared classes when Squot loads Tonel in Squeak 5.2

### ISSUE THREAD

**Issue by tcj** [hpi-swa/Squot#276]
Loading in Squeak 5.2 results in some classes being referenced which do not (and, I think, will not) exist:

TonelFileSystemUtils class>>default (DiskStore is Undeclared) 
TonelFileSystemUtils class>>directoryFromPath: (AbsolutePath is Undeclared) 
TonelFileSystemUtils class>>pathNameDelimiter (DiskStore is Undeclared) 

TonelFileSystemUtils class seems to be used by SquotTonel-Core and belongs to the package MonticelloTonel-FileSystem.

This TonelFileSystemUtils class _does_ seem to be used by various methods in TonelReader, TonelWriter, and TonelRepository.  

I assume this bug is only going to happen when loading Tonel in Squeak (or other non-Pharo platforms).  But I am not sure there is another Tonel-specific repo to file the bug against...

Sorry if this is not the proper style or place to report this.

**Comment by j4yk** [comment]
Thank you for the report. These undeclared references are remnants from moving https://github.com/squeak-smalltalk/squeak-tonel/tree/squeak from Pharo to Squeak. It seems though that the methods you named are never actually used since I did not run into any actual "UndefinedObject does not understand" errors. Did you?

The only senders I found are in the MCFileTree bunch of classes. So my guess is that they were copied from the FileSystemUtils for filetree, but then not all methods actually used for Tonel reading and writing.

I would transfer the issue to https://github.com/squeak-smalltalk/squeak-tonel, but somehow do not get that option. @fniephaus Are you able to transfer the issue?

**Comment by fniephaus** [comment]
I'm afraid I can't transfer the issue because `squeak-tonel` belongs to a different GitHub organization (`hpi-swa` vs. `squeak-smalltalk`).

**Comment by j4yk** [comment]
@tcj Can you please copy your text and open a new issue here: https://github.com/squeak-smalltalk/squeak-tonel/issues

**Comment by tom95** [comment]
I went ahead and created a PR on tonel and referenced this issue there.

**Comment by j4yk** [comment]
Merged the PR. I suppose chasing down the unused methods in those platform adapter classes is not worth the effort for now, so I will not open a followup issue for that.
