### ISSUE TITLE
Github and password authentication

### ISSUE THREAD

**Issue by darth-cheney** [hpi-swa/Squot#311]
Hi all,

It seems that Github has finally [deprecated password authentication](https://developer.github.com/changes/2020-02-14-deprecating-password-auth/). How else can I push to a protected remote via Squeak?

**Comment by j4yk** [comment]
Hi @darth-cheney,

You should be able to use an auth token as the password.

**Comment by darth-cheney** [comment]
Thanks, this works but I for whatever reason I have to hit "retry" 2 or three times each time I'm trying to push changes.

**Comment by j4yk** [comment]
What is the exact error message? Is this new or has it already happened before GitHub disabled password authentication?

**Comment by darth-cheney** [comment]
If I debug the message, the error is 401 Authorization Required. However, I have entered the credentials just before that. This problem **was** present before the password authentication change and I had just assumed it was occurring because Github was phasing out passwords

**Comment by j4yk** [comment]
I have also seen this intermittently. So far my current view of the problem is that it is either a bug in WebClient (not sending the credentials in the second request sometimes), or me misunderstanding a part of its API. I once had a breakpoint in one of WebClient's methods related to setting up the authentication headers and with the breakpoint present, the issue never appeared. This makes me lean more towards the "bug in WebClient" option... although this was a while ago and I don't know whether something changed in the meantime. If you didn't have the latest WebClient loaded yet, I would recommend you try that first.

I thought I already had an issue for this, but apparently not or I don't find it right now.

**Comment by darth-cheney** [comment]
I have some vague recollection of something mentioned either on Github or the squeak-dev list about WebClient not preserving authentication information properly across multiple requests. So it's likely something do to with that is the culprit here. Either way it's not too much of a hassle and the true source of this issue is dealt with so I'll close.
