### ISSUE TITLE
Load order

### ISSUE THREAD

**Issue by marceltaeumel** [hpi-swa/Squot#312]
The following "objects" are in the commit (?):

![grafik](https://user-images.githubusercontent.com/5765308/108048451-55d5dc80-7047-11eb-83d1-735976954066.png)

Due to a superclass dependency, "OpenGL/src/OpenGL" must load before  "GLFW/src/GLFW" but it does not, raising a dependency warning:

![grafik](https://user-images.githubusercontent.com/5765308/108048597-86b61180-7047-11eb-9d6c-e66bd5f0a09e.png)

Here are two questions:
 - Does Squot automatically determine the best load order?
 - Can the user specify the load order through the Git Browser?

Manually loading "3DTransform/src/3DTransform", then "OpenGL/src/OpenGL", then "GLFW/src/GLFW" works fine. Here is the load order that Squot determines:

'GLFW/src/GLFW' 'OpenGL/src/OpenGL' 'OpenGLCanvas/src/OpenGLCanvas' 'RenderThee/src/RenderThee' '3DTransform/src/3DTransform' 'Vulkan/src/Vulkan' 'LearnOpenGL/src/LearnOpenGL' 'ShaderLanguage/src/ShaderLanguage'

... which is not the required order.

**Comment by j4yk** [comment]
Hi Marcel,

Squot currently does not order them by itself at all. The compromise is that you can change the load order manually. Right click on the project > browse working copy, then use the buttons. This is not possible in the "objects" list because that reflects the state of the selected commit, so it would not make sense to reorder there.

If I remember correctly, new packages are just added at the end of the list, and packages added in the same batch are ordered alphabetically.

**Comment by j4yk** [comment]
Closing this as an answered question. Please reopen if there are any issues left with this, or create new issues.
