### ISSUE TITLE
Button to add co-authors while committing

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/Squot#334]
This should be integrated into Squot: <https://github.com/ShirleyNekoDev/Squot-CoAuthors>

It's been 2 years since I have been using it, but it was a helpful tool for me.

If @ShirleyNekoDev and @LeonBein would agree with MIT licensing of this repository, we could integrate this extension into Squot.

**Comment by LeonBein** [comment]
Definitely fine by me, I think the original code was by @ShirleyNekoDev.
@ShirleyNekoDev, what do you say?

**Comment by j4yk** [comment]
Just quickly looked at the code. Do I understand correctly that it adds a button to the save dialog which when clicked prompts you to select the co-authors, then these will be appended to the commit message (which can then still be edited)?

If that is it, nice. My only concern would be the precious space that the button might take up. Do you have a screenshot for me?

What is the use case? Pair programming attribution? Because otherwise if the methods come from various authors, why not let them make separate commits?

**Comment by LinqLover** [comment]
> What is the use case? Pair programming attribution?

Exactly, at least this was my main use case. 🙂

> My only concern would be the precious space that the button might take up. Do you have a screenshot for me?

Unfortunately not right now from my phone, but the button was way too large, yes. This is probably something which we would like to change. Maybe we could insert a menu item into the text pane for the commit message instead?

**Comment by LinqLover** [comment]
![image](https://user-images.githubusercontent.com/38782922/126010745-6cc7a12c-ae57-4161-9dbe-03580ad7ee47.png)

**Comment by j4yk** [comment]
If we could add a 60 character per line limitation to the text editor, having buttons on the right could actually make sense. Menu item also sounds good to me.

**Comment by LinqLover** [comment]
> If we could add a 60 character per line limitation to the text editor

Do we want that? I really think this should be a responsibility of tooling these days. I'm not really a big fan of pictures like this: :-)

![image](https://user-images.githubusercontent.com/38782922/126011400-0938f44a-5fc1-4681-8af9-cc5924c4eb21.png)

But yes, there might be some other pre-commit actions, maybe to create an overview of slips in the working copy ...

**Comment by j4yk** [comment]
In the Smalltalk tools, limiting to 60 chars does not make much sense. But since this is also about Git, one should also mind the conventions formed by console users. For the headline in commit messages it also makes sense due to the limited space in commit lists of all kinds. Eclipse has the nice solution of automatically and responsively inserting line breaks, so if you edit the middle of the sentence, the the words move around the line breaks as well. But it is actually off-topic in this issue here.

**Comment by LinqLover** [comment]
Off-topic, but still interesting. :-) I agree that the headline should not be too long - looks strange in the Squit Browser, too - but for the rest of the messages, I actually don't see why git on the CLI could not wrap the message by itself. Removing the linebreaks at a later point in time is much harder than inserting them IMHO.

**Comment by ShirleyNekoDev** [comment]
I've added the MIT license to my repository.
Glad you found my tool useful and want to develop it into a full feature! Feel free to integrate or modify the code for your convenience :)

**Comment by j4yk** [comment]
Merged the other repository, merged the copyright into the LICENSE file and merged the former README.md into the main README.md.

My only concern is that it is not very discoverable in the image how to modify the authors list. Any suggestions?

**Comment by LinqLover** [comment]
Very nice, thank you!

> My only concern is that it is not very discoverable in the image how to modify the authors list. Any suggestions?

Add a "add new co-author" item to the top/bottom of the list, and when it is chosen, ask the user for name and e-mail address in two dialogs (or a single merged one)? :-)

**Comment by j4yk** [comment]
> Add a "add new co-author" item to the top/bottom of the list, and when it is chosen, ask the user for name and e-mail address in two dialogs (or a single merged one)? :-)

I added an item to just open the browser on the method. Please check it out.

**Comment by j4yk** [comment]
Since I have not received any further feedback, I will assume that it is fine as it is.

**Comment by LinqLover** [comment]
Thank you! 🎉
