### ISSUE TITLE
Feature request: Support Cmd + m and Cmd + n in commit dialog

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/Squot#337]
Maybe also <kbd>Cmd</kbd> + <kbd>N</kbd> (class references). What about <kbd>Cmd</kbd> + <kbd>a</kbd> (assignments) and <kbd>Cmd</kbd> + <kbd>r</kbd> (references)?

Analogously to "browse full (b)".

**Comment by j4yk** [comment]
Workaround: select the tree node, then select the identifier in the text on the right and use cmd+m and cmd+n there. That is what I do.

Maybe one could find a neat way to hook up the capabilities of the TextEditor with the menu of the diff nodes.

Unfortunately, this is currently Morphic-specific as far as I know. Although it would not be much of a problem in practice today.

**Comment by LinqLover** [comment]
I thought this should be pretty easy to implement, just add some additional shortcuts to the tree shortcut list? Trees are not supported in MVC at the moment either way ...

**Comment by j4yk** [comment]
Yes it should not be too hard. I only do not really like to duplicate the TextEditor code in Squot. :-)

**Comment by LinqLover** [comment]
I think we do not need anything else than the SystemNavigation protocol for this, do we?

**Comment by j4yk** [comment]
Since this is not about editing, yes, only navigation. But as you have mentioned, it has quite a few actions.

**Comment by j4yk** [comment]
I think I do not want to add this. The save and merge dialogs are not system navigation tools or general code browsers. With the "browse full" action you can make the transition to the regular tools, in which you can do all the things you requested. Relying on the ability to do code navigation everywhere in Smalltalk, I defer to the text editor on the right. Analogously, I also would not add the usual button strip with browse, senders, implementors, ... to those dialogs.

If the regular navigation actions were implemented as services in the Squeak services framework, I could easily add all actions which are system-wide defined for methods, classes etc. to a menu without introducing extra redundant code to maintain. But since that is not the case, I do not think it is worth the effort.

**Comment by LinqLover** [comment]
> If the regular navigation actions were implemented as services in the Squeak services framework, I could easily add all actions which are system-wide defined for methods, classes etc. to a menu without introducing extra redundant code to maintain. But since that is not the case, I do not think it is worth the effort.

You could subclass from `StringHolder`, but yes, this is currently not an idea solution.
