### ISSUE TITLE
MessageNotUnderstood: NotFound class>>signalFor:

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/Squot#342]
There are [5 senders of `NotFound class >> #signalFor:`](https://github.com/hpi-swa/Squot/search?q=signalFor%3A&type=code) but it is still not implemented in Squeak, as you already seem to have noticed in cb7cced4d56713caa07b3f7cb53fa9fe9b92a10a. :-)

**Comment by j4yk** [comment]
Thank you for the reminder.

The signalFor: method is provided by STON, on which Squot currently depends anyway. So is this a cleanliness issue or did you also experience a failure because of this?

The commit you linked is in FileSystem, which does not depend on STON, therefore it was a real issue there. (And hard to notice because I do not regularly use any images with FileSystem but without Squot and therefore STON.)

**Comment by j4yk** [comment]
Looks like it is left over in my image from here: https://github.com/fniephaus/ston/tree/fniephaus-patch-3/repository/STON-Squeak-Core.package

Then agreed, it should not be used.
