### ISSUE TITLE
[MacOS 12] Potential race condition when merging branches of the sandblocks repository

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [hpi-swa/Squot#355]
Hello there,

the Squeak Git Browser seems to have a race condition on Mac OS 12 when trying to merge branches on the sandblocks Repo. It always fails to read a certain file (see image) and the shows an error. The problem is that this file exists and if I open the debugger and restart the method (FSFielHandle >> open) that tries to read the file, the method now succeeds without an error. After that I can simply proceed and the merging works as expected.
Here is an image of the debugger opened upon receiving the error:
<img width="1434" alt="Bildschirmfoto 2021-12-03 um 16 18 33" src="https://user-images.githubusercontent.com/39529669/144638392-d6d89c25-ce0a-40f2-9f57-bebb8f36d5c7.png">

**Comment by j4yk** [comment]
Hi @MichaelBuessemeyer ,

That is odd since FileSystem-Git itself does not do any multi-processing. Moreover, the pack file is not created during a merge, but during the clone or during a fetch (although in Squeak it is not kept after a fetch at the moment).

Which version do you have installed? (master branch, develop branch, or:

`(((PackageInfo named: 'FileSystem-Git') methods collect: #timeStamp) collect: [:each | TimeStamp fromMethodTimeStamp: each]) max`
and
`((Smalltalk organization categories select: [:ea | ea beginsWith: 'FS-']) collect: [:ea | ((Smalltalk organization classesIn: ea) collect: [:eaClass | (eaClass methodDict values collect: [:eaM | eaM timeStamp ifEmpty: [TimeStamp epoch] ifNotEmpty: [TimeStamp fromMethodTimeStamp: eaM timeStamp]]) ifEmpty: [TimeStamp epoch] ifNotEmpty: [:it | it max]]) ifEmpty: [TimeStamp epoch] ifNotEmpty: [:it | it max]]) max`
).

Seems like we have to find out why the basicOpen fails in the first place.

**Comment by MichaelBuessemeyer** [comment]
Hi @j4yk,

my version is the versions are 
> (((PackageInfo named: 'FileSystem-Git') methods collect: #timeStamp) collect: [:each | TimeStamp fromMethodTimeStamp: each]) max

`10 September 2021 8:28 pm`, 
> ((Smalltalk organization categories select: [:ea | ea beginsWith: 'FS-']) collect: [:ea | ((Smalltalk organization classesIn: ea) collect: [:eaClass | (eaClass methodDict values collect: [:eaM | eaM timeStamp ifEmpty: [TimeStamp epoch] ifNotEmpty: [TimeStamp fromMethodTimeStamp: eaM timeStamp]]) ifEmpty: [TimeStamp epoch] ifNotEmpty: [:it | it max]]) ifEmpty: [TimeStamp epoch] ifNotEmpty: [:it | it max]]) max

` 30 October 2021 11:36 pm ` 
and my OS is at `12.0.1 (21A559)`.

**Comment by MichaelBuessemeyer** [comment]
Just some additional information:

I got this error since last Saturday: 27th Nov

**Comment by LinqLover** [comment]
See also: https://github.com/cmfcmf/MagicMouse/issues/12#issuecomment-986065908

**Comment by j4yk** [comment]
@MichaelBuessemeyer Did you update Squeak or the VM around that day?

**Comment by LinqLover** [comment]
> @MichaelBuessemeyer Did you update Squeak or the VM around that day?

An update is not necessary to reproduce the issue, IIUC this is a new kind of millennium problem - some overflowing data type for a time value. Maybe @tom95 will elaborate on this on squeak-dev soon. 😅

**Comment by tom95** [comment]
@MichaelBuessemeyer could you try and see if it's still reproducible when you get a chance and reopen the issue if yes? There was a bug in the VM version you were using that didn't allow for file handles to be opened intermittently, so this could have been a likely cause.

If you can still reproduce it, we should make sure you're on the latest version of both the Squeak VM and Squot and then do one last check. I can help you set those up, should be pretty quick :)
