### ISSUE TITLE
Warn before force pushing commits

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/Squot#93]
By default, commits are still force pushed which is not a good idea.
Instead, the user should be asked for confirmation to proceed instead.

**Comment by justus-hildebrand** [comment]
bump

**Comment by tom95** [comment]
Similarly, committing from within squeak does not check what state the repo it commits to is in. Changes pulled via the git cli will be overwritten by a commit from squot.
Instead, squot should probably keep track of the version that was last merged into the image and force the user to do a merge before committing anything new.

**Comment by j4yk** [comment]
I am at work today, so please be patient. In case you seem to have "lost" commits, please use the reflog to recover them. @tom95 This sounds strange, since Squot commits on top of refs (branches), not on top of single commits, so committing in Squot should not prune commits created elsewhere. However, committing in Squot seeks to apply the state from the image to the versioned files, so you might see a lot of "reverts" unless you carefully select what is included in a commit. Is this what you mean?

Forcing someone to merge before committing anything new sounds very svn-like... ;-)

**Comment by j4yk** [comment]
Please review and try db7e8ea on the develop branch.
